[env:esp32-c3-round-dashboard]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
board_build.flash_size = 4MB
board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/bump_build.py

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  h2zero/NimBLE-Arduino
  moononournation/GFX Library for Arduino@1.4.7
